import { GraphQLClient } from "graphql-request";
import { QueryClient } from "react-query";

import { getSdk } from "@/graphql/generated/graphql";

const gqlClient = new GraphQLClient(
  `${process.env.FRONT_END_URL}/api/graphql/`
);
export const {
  // QUERY
  getDogs,
  users,
  Login,
  UserById,
  FindRole,
  FindRolesByUserId,
  FindRelatingUsers,
  FindMyUsers,
  ManageRolesListing,
  FindRoleById,
  FindAllReportTemplates,
  FindAllPackages,
  FindPackageById,
  TrackClientAdmins,
  TrackParticularClientRecord,
  GetUserPackageModuleById,
  FindAllSubAdminPayments,
  GetSubAdminList,
  RequestedLocations,
  GetLocationById,
  FindAllDepartments,
  FindDepartmentsByOwnerId,
  FindDepartmentById,
  GetPost,
  FindAllEmployees,
  FindEmployeeById,
  GetUserParks,
  GetFacilities,
  UserLocations,
  FindActivityLogByClientAdminId,
  FindActivityLogByUserId,
  FindActivityLogById,
  FindAllReports,
  FindUserReportSubmissionById,
  GetClientSecret,
  GetClientSecretForSubscriber,
  GetTrainingById,
  GetAssignedTrainingById,
  GetMyTrainings,
  GetUserTrainingSession,
  FindAllTasks,
  TrackAllTasks,
  FindAssignedTaskById,
  FindTaskById,
  GetEmailAndNotificationById,
  GetEmailAndNotificationByCreatorId,
  GetUserNotifications,
  GetIncidentReportsForClientDashboardStats,
  GetClientDashboardStats,
  GetSuperAdminDashboardStats,
  GetAllClientAdmins,
  GetAllSubscriptions,
  GetAllParks,
  GetPointsOfInterest,
  GetFailedVAT,
  GetPectoraAuth,

  // MUTATIONS
  forgetPassword,
  ResetPassword,
  VerifyOtp,
  AddUserAdmin,
  CreateSubAdmin,
  RegisterClient,
  ActivateSubAdminAfterSubscription,
  AddPackage,
  AddRole,
  FindTemplateById,
  AddReportTemplate,
  DeleteReportTemplate,
  UpdateTemporaryPassword,
  UpdateSubAdmin,
  UpdateAdminUser,
  UpdateRole,
  UpdatePackage,
  DeleteSubscriptionPackage,
  UpdateReportTemplate,
  OnboardSubAdmin,
  DeleteAdminUser,
  DeleteRole,
  AddAnotherLocation,
  AcceptLocationRequest,
  UpdateFacilityRequest,
  UpdateProfile,
  ChangePassword,
  UpdateEmail,
  CreateEmployee,
  UpdateEmployee,
  DeleteEmployee,
  AddDepartment,
  UpdateDepartment,
  DeleteDepartment,
  ModifyPackage,
  CreateActivityLog,
  AssignReportTemplate,
  AddTrainingSession,
  ApproveReportSubmission,
  UpdateTraining,
  DeleteTraining,
  AssignTrainingSession,
  AssignInService,
  CreateTask,
  UpdateTask,
  DeleteTask,
  AssignTask,
  ApproveSubmission,
  FindSubAdminPaymenteById,
  AddEmailAndNotification,
  EditEmailAndNotification,
  AssignEmailAndNotification,
  UpdateUserFields,
  MarkAsRead,
  DeleteEmailAndNotification,
  PostTicker,
  CreateStripeCustomer,
  AddPointOffInterest,
  UpdatePointOffInterest,
  DeletePointOffInterest,
  AttachTaskToTraining,
  AddPectoraAuth,
} = getSdk(gqlClient);

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnMount: false,
      refetchOnWindowFocus: false,
      refetchOnReconnect: false,
    },
  },
});
