import { ChevronDownIcon } from "@chakra-ui/icons";
import {
  AiOutlineApartment,
  AiOutlineDelete,
  AiOutlineDollarCircle,
  AiTwotoneInfoCircle,
} from "react-icons/ai";
import {
  BiAccessibility,
  BiCheck,
  BiCommentAdd,
  BiRefresh,
  BiSolidUserCheck,
  BiSolidUserX,
  BiTimeFive,
} from "react-icons/bi";
import {
  BsCalculatorFill,
  BsCalendar2Date,
  BsCalendarDate,
  BsCheck2,
  BsCheckLg,
  BsChevronDown,
  BsChevronLeft,
  BsChevronUp,
  BsEyeFill,
  BsEyeSlashFill,
  BsFiletypeCsv,
  BsFiletypeDocx,
  BsFiletypeTxt,
  BsFillCloudUploadFill,
  BsFillMoonFill,
  BsFillSunFill,
  BsInfoCircle,
  BsInputCursorText,
  BsPersonFillAdd,
  BsPersonFillCheck,
  BsQuestionCircle,
} from "react-icons/bs";
import { CgChevronLeft, CgChevronRight } from "react-icons/cg";
import {
  CiCalculator1,
  CiFileOn,
  CiFilter,
  CiShare1,
  CiUser,
} from "react-icons/ci";
import {
  FaHandHoldingUsd,
  FaRegFile,
  FaTasks,
  FaUser,
  FaUserCheck,
  FaUserCog,
  FaUserPlus,
  FaUsers,
  FaUserTimes,
} from "react-icons/fa";
import { FaRegFilePdf } from "react-icons/fa6";
import {
  FiCompass,
  FiEdit,
  FiEdit2,
  FiFileText,
  FiHelpCircle,
  FiMenu,
  FiPlusCircle,
  FiSettings,
  FiStar,
  FiTrendingUp,
  FiUser,
} from "react-icons/fi";
import { GiTeacher } from "react-icons/gi";
import { GoHeading, GoPackage, GoSingleSelect } from "react-icons/go";
import { GrAddCircle, GrFormClose } from "react-icons/gr";
import {
  HiArrowSmDown,
  HiArrowSmUp,
  HiDocumentReport,
  HiEye,
  HiEyeOff,
  HiUser,
  HiUsers,
} from "react-icons/hi";
import { ImList2, ImNewTab, ImSearch } from "react-icons/im";
import {
  IoIosColorPalette,
  IoMdAdd,
  IoMdAttach,
  IoMdClose,
  IoMdNotificationsOutline,
  IoMdRemove,
} from "react-icons/io";
import { IoAlertCircleOutline } from "react-icons/io5";
import {
  LuMove,
  LuNetwork,
  LuPackageOpen,
  LuPackagePlus,
} from "react-icons/lu";
import {
  MdAdd,
  MdAddLocation,
  MdAddTask,
  MdAdminPanelSettings,
  MdAppSettingsAlt,
  MdCheckCircle,
  MdEditDocument,
  MdLocationOn,
  MdManageAccounts,
  MdModeEditOutline,
  MdNumbers,
  MdOutlineAddLocation,
  MdOutlineArrowBack,
  MdOutlineAttachMoney,
  MdOutlineCircleNotifications,
  MdOutlineContentPaste,
  MdOutlineManageSearch,
  MdOutlineMyLocation,
  MdPersonAddAlt,
  MdSettings,
} from "react-icons/md";
import { PiParagraph } from "react-icons/pi";
import {
  RiAccountPinBoxFill,
  RiCustomerService2Fill,
  RiDashboard2Line,
  RiImageAddFill,
  RiMoneyDollarCircleLine,
  RiUploadCloud2Fill,
  RiUserLocationFill,
  RiVideoUploadFill,
} from "react-icons/ri";
import { RxActivityLog, RxCaretSort, RxCross2 } from "react-icons/rx";
import { SiMicrosoftexcel } from "react-icons/si";
import {
  TbFilePencil,
  TbFilePlus,
  TbFileSearch,
  TbFileSettings,
  TbFilter,
  TbHome2,
  TbReportAnalytics,
  TbSelect,
  TbTools,
} from "react-icons/tb";
import { TfiEmail } from "react-icons/tfi";
import { TiArrowSortedDown, TiArrowSortedUp, TiInfo } from "react-icons/ti";
import { VscTasklist } from "react-icons/vsc";

export {
  AiOutlineDelete,
  AiOutlineDollarCircle,
  AiTwotoneInfoCircle,
  AiOutlineApartment,
  BiAccessibility,
  BiTimeFive,
  BiSolidUserX,
  BiSolidUserCheck,
  BiCheck,
  BiCommentAdd,
  BiRefresh,
  BsFillMoonFill,
  BsFillSunFill,
  BsChevronDown,
  BsCalendar2Date,
  BsCheckLg,
  BsEyeFill,
  BsInfoCircle,
  BsEyeSlashFill,
  BsPersonFillAdd,
  BsInputCursorText,
  BsQuestionCircle,
  BsFiletypeCsv,
  BsFiletypeDocx,
  BsFiletypeTxt,
  BsCalculatorFill,
  BsChevronUp,
  BsPersonFillCheck,
  BsCalendarDate,
  BsChevronLeft,
  BsCheck2,
  BsFillCloudUploadFill,
  ChevronDownIcon,
  CiShare1,
  CiCalculator1,
  CiFilter,
  CiUser,
  CiFileOn,
  FaUsers,
  FaUserCog,
  FaHandHoldingUsd,
  FaUserCheck,
  FaUserTimes,
  FaRegFile,
  FaUser,
  FaUserPlus,
  FaTasks,
  FiCompass,
  FiPlusCircle,
  FiEdit,
  FiEdit2,
  FiFileText,
  FiHelpCircle,
  FiMenu,
  FiSettings,
  FiStar,
  FiTrendingUp,
  FiUser,
  FaRegFilePdf,
  HiUsers,
  HiDocumentReport,
  HiArrowSmUp,
  HiArrowSmDown,
  HiUser,
  GoPackage,
  GoHeading,
  GoSingleSelect,
  GiTeacher,
  GrAddCircle,
  GrFormClose,
  HiEye,
  HiEyeOff,
  ImSearch,
  ImList2,
  ImNewTab,
  IoMdAdd,
  IoMdRemove,
  IoAlertCircleOutline,
  IoMdAttach,
  IoIosColorPalette,
  IoMdNotificationsOutline,
  IoMdClose,
  MdPersonAddAlt,
  MdAddLocation,
  MdLocationOn,
  MdAdd,
  MdNumbers,
  MdAddTask,
  MdModeEditOutline,
  MdAdminPanelSettings,
  MdAppSettingsAlt,
  MdCheckCircle,
  MdOutlineAddLocation,
  MdManageAccounts,
  MdOutlineArrowBack,
  MdOutlineAttachMoney,
  MdOutlineContentPaste,
  MdOutlineCircleNotifications,
  MdSettings,
  MdEditDocument,
  MdOutlineMyLocation,
  MdOutlineManageSearch,
  LuPackageOpen,
  LuPackagePlus,
  LuNetwork,
  LuMove,
  PiParagraph,
  RiCustomerService2Fill,
  RiMoneyDollarCircleLine,
  RxCaretSort,
  RxCross2,
  RiDashboard2Line,
  SiMicrosoftexcel,
  TbTools,
  TbFileSettings,
  TbFilePlus,
  TbFilter,
  TbHome2,
  TbSelect,
  TbFileSearch,
  TbFilePencil,
  TbReportAnalytics,
  TfiEmail,
  TiArrowSortedUp,
  TiInfo,
  TiArrowSortedDown,
  VscTasklist,
  RiImageAddFill,
  RiVideoUploadFill,
  RiAccountPinBoxFill,
  RiUserLocationFill,
  RiUploadCloud2Fill,
  CgChevronLeft,
  CgChevronRight,
  RxActivityLog,
};
