name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.ELLISDOCS_SSH_PRIVATE_KEY }}

      - name: Connect to EC2 and pull changes
        run: |
          # Connect to EC2 instance
          ssh -i ${{ secrets.ELLISDOCS_SSH_PRIVATE_KEY }} ubuntu@"$107.23.119.73" << EOF
          
          # Navigate to the target directory
          cd /var/www/ellis-docs/

          # Pull changes from the repository
          git pull origin main

          # Exit the SSH session
          exit
          EOF
          